In [1]:
import pandas as pd

file_path = "../data/raw/UK-HPI-full-file-2025-05.csv"

df = pd.read_csv(file_path)

df.head()

,Date,RegionName,AreaCode,AveragePrice,Index,IndexSA,1m%Change,12m%Change,AveragePriceSA,SalesVolume,...,NewPrice,NewIndex,New1m%Change,New12m%Change,NewSalesVolume,OldPrice,OldIndex,Old1m%Change,Old12m%Change,OldSalesVolume
0,01/01/2004,Aberdeenshire,S12000034,84638,41.1,NaN,NaN,NaN,NaN,388.0,...,112843.0,40.7,NaN,NaN,103.0,81273.0,41.0,NaN,NaN,285.0
1,01/02/2004,Aberdeenshire,S12000034,84623,41.1,NaN,0.0,NaN,NaN,326.0,...,113061.0,40.8,0.2,NaN,107.0,81194.0,40.9,-0.1,NaN,219.0
2,01/03/2004,Aberdeenshire,S12000034,86536,42.1,NaN,2.3,NaN,NaN,453.0,...,115218.0,41.6,1.9,NaN,140.0,83137.0,41.9,2.4,NaN,313.0
3,01/04/2004,Aberdeenshire,S12000034,87373,42.5,NaN,1.0,NaN,NaN,571.0,...,115247.0,41.6,0.0,NaN,180.0,84241.0,42.5,1.3,NaN,391.0
4,01/05/2004,Aberdeenshire,S12000034,89493,43.5,NaN,2.4,NaN,NaN,502.0,...,117377.0,42.4,1.8,NaN,167.0,86466.0,43.6,2.6,NaN,335.0

In [2]:
df.shape

(146250, 54)

In [3]:
df.columns

Index(['Date', 'RegionName', 'AreaCode', 'AveragePrice', 'Index', 'IndexSA',
       '1m%Change', '12m%Change', 'AveragePriceSA', 'SalesVolume',
       'DetachedPrice', 'DetachedIndex', 'Detached1m%Change',
       'Detached12m%Change', 'SemiDetachedPrice', 'SemiDetachedIndex',
       'SemiDetached1m%Change', 'SemiDetached12m%Change', 'TerracedPrice',
       'TerracedIndex', 'Terraced1m%Change', 'Terraced12m%Change', 'FlatPrice',
       'FlatIndex', 'Flat1m%Change', 'Flat12m%Change', 'CashPrice',
       'CashIndex', 'Cash1m%Change', 'Cash12m%Change', 'CashSalesVolume',
       'MortgagePrice', 'MortgageIndex', 'Mortgage1m%Change',
       'Mortgage12m%Change', 'MortgageSalesVolume', 'FTBPrice', 'FTBIndex',
       'FTB1m%Change', 'FTB12m%Change', 'FOOPrice', 'FOOIndex', 'FOO1m%Change',
       'FOO12m%Change', 'NewPrice', 'NewIndex', 'New1m%Change',
       'New12m%Change', 'NewSalesVolume', 'OldPrice', 'OldIndex',
       'Old1m%Change', 'Old12m%Change', 'OldSalesVolume'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146250 entries, 0 to 146249
Data columns (total 54 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Date                    146250 non-null  object
 1   RegionName              146250 non-null  object
 2   AreaCode                146250 non-null  object
 3   AveragePrice            146250 non-null  int64
 4   Index                   146250 non-null  float64
 5   IndexSA                 5139 non-null    float64
 6   1m%Change               145797 non-null  float64
 7   12m%Change              141390 non-null  float64
 8   AveragePriceSA          5139 non-null    float64
 9   SalesVolume             141783 non-null  float64
 10  DetachedPrice           139533 non-null  float64
 11  DetachedIndex           139533 non-null  float64
 12  Detached1m%Change       139138 non-null  float64
 13  Detached12m%Change      134817 non-null  float64
 14  SemiDetachedPrice       139533 non-null  float64
 15  SemiDetachedIndex       139533 non-null  float64
 16  SemiDetached1m%Change   139138 non-null  float64
 17  SemiDetached12m%Change  134817 non-null  float64
 18  TerracedPrice           139644 non-null  float64
 19  TerracedIndex           139644 non-null  float64
 20  Terraced1m%Change       139248 non-null  float64
 21  Terraced12m%Change      134916 non-null  float64
 22  FlatPrice               139898 non-null  float64
 23  FlatIndex               139898 non-null  float64
 24  Flat1m%Change           139502 non-null  float64
 25  Flat12m%Change          135170 non-null  float64
 26  CashPrice               63112 non-null   float64
 27  CashIndex               63112 non-null   float64
 28  Cash1m%Change           62720 non-null   float64
 29  Cash12m%Change          58408 non-null   float64
 30  CashSalesVolume         62326 non-null   float64
 31  MortgagePrice           63112 non-null   float64
 32  MortgageIndex           63112 non-null   float64
 33  Mortgage1m%Change       62720 non-null   float64
 34  Mortgage12m%Change      58408 non-null   float64
 35  MortgageSalesVolume     62326 non-null   float64
 36  FTBPrice                63508 non-null   float64
 37  FTBIndex                63508 non-null   float64
 38  FTB1m%Change            63116 non-null   float64
 39  FTB12m%Change           58804 non-null   float64
 40  FOOPrice                63112 non-null   float64
 41  FOOIndex                63112 non-null   float64
 42  FOO1m%Change            62720 non-null   float64
 43  FOO12m%Change           58408 non-null   float64
 44  NewPrice                138906 non-null  float64
 45  NewIndex                138906 non-null  float64
 46  New1m%Change            138510 non-null  float64
 47  New12m%Change           134178 non-null  float64
 48  NewSalesVolume          136334 non-null  float64
 49  OldPrice                139110 non-null  float64
 50  OldIndex                139110 non-null  float64
 51  Old1m%Change            138714 non-null  float64
 52  Old12m%Change           134382 non-null  float64
 53  OldSalesVolume          139096 non-null  float64
dtypes: float64(50), int64(1), object(3)
memory usage: 60.3+ MB

In [5]:
df.isna().sum()

Date                           0
RegionName                     0
AreaCode                       0
AveragePrice                   0
Index                          0
IndexSA                   141111
1m%Change                    453
12m%Change                  4860
AveragePriceSA            141111
SalesVolume                 4467
DetachedPrice               6717
DetachedIndex               6717
Detached1m%Change           7112
Detached12m%Change         11433
SemiDetachedPrice           6717
SemiDetachedIndex           6717
SemiDetached1m%Change       7112
SemiDetached12m%Change     11433
TerracedPrice               6606
TerracedIndex               6606
Terraced1m%Change           7002
Terraced12m%Change         11334
FlatPrice                   6352
FlatIndex                   6352
Flat1m%Change               6748
Flat12m%Change             11080
CashPrice                  83138
CashIndex                  83138
Cash1m%Change              83530
Cash12m%Change             87842
CashSalesVolume            83924
MortgagePrice              83138
MortgageIndex              83138
Mortgage1m%Change          83530
Mortgage12m%Change         87842
MortgageSalesVolume        83924
FTBPrice                   82742
FTBIndex                   82742
FTB1m%Change               83134
FTB12m%Change              87446
FOOPrice                   83138
FOOIndex                   83138
FOO1m%Change               83530
FOO12m%Change              87842
NewPrice                    7344
NewIndex                    7344
New1m%Change                7740
New12m%Change              12072
NewSalesVolume              9916
OldPrice                    7140
OldIndex                    7140
Old1m%Change                7536
Old12m%Change              11868
OldSalesVolume              7154
dtype: int64

In [6]:
df['Date'] = pd.to_datetime(df['Date'])

In [7]:
df['Date'].dtype

dtype('<M8[ns]')

In [8]:
df = df.sort_values('Date')
df = df.reset_index(drop=True)

In [9]:
cols_to_keep = [
    'Date','RegionName','AveragePrice','SalesVolume',
    'DetachedPrice','SemiDetachedPrice',
    'TerracedPrice','FlatPrice',
    'CashPrice','MortgagePrice'
]

housing = df[cols_to_keep]
housing.head()

,Date,RegionName,AveragePrice,SalesVolume,DetachedPrice,SemiDetachedPrice,TerracedPrice,FlatPrice,CashPrice,MortgagePrice
0,1968-01-04,West Midlands Region,3188,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1968-01-04,Yorkshire and The Humber,2553,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1968-01-04,London,4730,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1968-01-04,Northern Ireland,3465,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1968-01-04,Scotland,2738,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
housing.isna().sum()

Date                     0
RegionName               0
AveragePrice             0
SalesVolume           4467
DetachedPrice         6717
SemiDetachedPrice     6717
TerracedPrice         6606
FlatPrice             6352
CashPrice            83138
MortgagePrice        83138
dtype: int64

In [15]:
housing = housing.ffill()
housing = housing.bfill()

In [16]:
housing.isna().sum()

Date                 0
RegionName           0
AveragePrice         0
SalesVolume          0
DetachedPrice        0
SemiDetachedPrice    0
TerracedPrice        0
FlatPrice            0
CashPrice            0
MortgagePrice        0
dtype: int64

In [20]:
housing.to_csv("../data/processed/cleaned_housing.csv", index=False)